# Generated by Django 5.2.18 on 2026-10-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('invite_type', models.CharField(choices=[('AD', 'All day'), ('EV', 'Evening')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('needs_own_rsvp', models.BooleanField(default=True)),
                ('reply_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('TBC', 'Not yet replied')], default='TBC', max_length=3)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rsvp.household')),
            ],
        ),
    ]
